openapi: 3.0.3
info:
  title: CTC Guarantee Balance
  contact: {}
  version: '2.0'
  description: |
    # Overview
    Use the CTC Guarantee Balance API to provide traders with up-to-date
    information about how much of their guarantee funds they have left to
    use when organising transit movements. For a detailed overview of v2.0 of
    the API, see [CTC Guarantee Balance API phase 5 service guide](/guides/ctc-guarantee-balance-phase5-service-guide).
servers:
  - url: https://test-api.service.hmrc.gov.uk
    description: Sandbox
  - url: https://api.service.hmrc.gov.uk
    description: Production
    variables: {}
paths:
  /customs/guarantees/{grn}/balance:
    post:
      summary: Get a balance
      description: Get the balance associated with a guarantee reference number (GRN).
      operationId: getGuaranteeBalance
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/contentTypeHeader'
        - in: path
          name: grn
          schema:
            type: string
            pattern: '^[0-9]{2}[A-Z]{2}[A-Z0-9]{12}[0-9]$'
          required: true
          description: The guarantee reference number (GRN) of the guarantee.
      requestBody:
        content:
          application/json:
            schema:
              allOf:
                - $ref: '#/components/schemas/CustomsGuaranteesBalancesrequest'
                - example:
                    accessCode: ABC1
            example:
              accessCode: ABC1
        required: true
      responses:
        '200':
          description: A successful balance request response
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/GetBalanceOk'
                  - example:
                      balance: 12345678.90
                      currency: GBP
              example:
                _links:
                  self:
                    href: /customs/guarantees/23GB0123456789AB2/balance
                balance: 12345678.90
                currency: GBP
        '400':
          description: Bad request or invalid guarantee type
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/BadRequest'
                  - $ref: '#/components/schemas/InvalidGuaranteeType'
        '404':
          description: Guarantee not found or invalid access code
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/NotFound'
                  - description: The guarantee reference number or access code did not match an existing guarantee.
                    example:
                      code: NOT_FOUND
                      message: The guarantee reference number or access code did not match an existing guarantee.
              example:
                code: NOT_FOUND
                message: The guarantee reference number or access code did not match an existing guarantee.
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/AcceptHeaderInvalid'
                  - example:
                      code: ACCEPT_HEADER_INVALID
                      message: The Accept header must be set to application/vnd.hmrc.2.0+json to use this resource.
              example:
                code: ACCEPT_HEADER_INVALID
                message: The Accept header must be set to application/vnd.hmrc.2.0+json to use this resource.
        '429':
          description: Too Many Requests
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/TooManyRequests'
                  - description: The rate limit was exceeded for the current user and guarantee.
                    example:
                      code: TOO_MANY_REQUESTS
                      message: Guarantee balance not found.
              example:
                code: TOO_MANY_REQUESTS
                message: Too many requests.
      deprecated: false
      security:
        - userRestricted:
            - common-transit-convention-guarantee-balance
components:
  schemas:
    errorResponse:
      title: errorResponse
      required:
        - code
      type: object
      properties:
        code:
          type: string
    hal-document-schema.json:
      title: hal-document-schema.json
      type: object
      description: Hypertext Application Language (HAL) document.
      properties:
        _links:
          allOf:
            - $ref: '#/components/schemas/Links'
            - description: An object containing links to other resources.
        _embedded:
          type: object
          additionalProperties: {}
          description: An object containing embedded resources.
    CustomsGuaranteesBalancesrequest:
      title: CustomsGuaranteesBalancesrequest
      description: A balance request for the CTC Guarantee Balance API.
      required:
        - accessCode
      type: object
      properties:
        accessCode:
          maxLength: 4
          minLength: 4
          type: string
          description: The `accessCode` granting access to make use of the guarantee.
    GetBalanceOk:
      title: Balance request successful
      description: A successful balance response.
      required:
        - balance
      type: object
      properties:
        _links:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/halLink'
          description: An object containing links to other resources.
        _embedded:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/hal-document-schema.json'
          description: An object containing embedded resources.
        balance:
          description: The guarantee's balance.
          type: number
        currency:
          pattern: ^[A-Z]{3}$
          type: string
          description: >-
            The alphanumeric 3-character ISO currency code of the currency in
            which the balance is held.
    BadRequest:
      title: Bad Request
      description: An error in the supplied payload, or the guarantee reference number did not match the expected format.
      required:
        - code
        - message
      type: object
      properties:
        code:
          enum:
            - BAD_REQUEST
          type: string
        message:
          type: string
          description: The description of the error.
      example:
        code: BAD_REQUEST
        message: The access code was not supplied.
    InvalidGuaranteeType:
      title: Invalid Guarantee Type
      description: The supplied guarantee reference number refers to a guarantee that is not type 0, 1 or 9, and so a balance could not be obtained.
      required:
        - code
        - message
      type: object
      properties:
        code:
          enum:
            - INVALID_GUARANTEE_TYPE
          type: string
        message:
          type: string
          description: The description of the error.
      example:
        code: INVALID_GUARANTEE_TYPE
        message: Guarantee type is not supported.
    NotFound:
      title: NotFound
      description: A guarantee was not found that matched the supplied guarantee reference number and access code.
      required:
        - code
        - message
      type: object
      properties:
        code:
          enum:
            - NOT_FOUND
          type: string
        message:
          type: string
          description: The description of the error.
    TooManyRequests:
      title: TooManyRequests
      description: The rate limit was exceeded for this user and guarantee.
      required:
        - code
        - message
      type: object
      properties:
        code:
          enum:
            - TOO_MANY_REQUESTS
          type: string
        message:
          type: string
          description: The description of the error.
    AcceptHeaderInvalid:
      title: AcceptHeaderInvalid
      description: The `Accept` header was not set to `application/vnd.hmrc.2.0+json`.
      required:
        - code
        - message
      type: object
      properties:
        code:
          enum:
            - ACCEPT_HEADER_INVALID
          type: string
        message:
          type: string
          description: The description of the error.
    halLink:
      title: halLink
      description: Hypertext Application Language (HAL) link object.
      required:
        - href
      type: object
      properties:
        href:
          type: string
          description: A link to another resource.
    Links:
      title: Links
      description: An object containing links to other resources.
      type: object
      properties:
        self:
          allOf:
            - $ref: '#/components/schemas/halLink'
            - description: Hypertext Application Language (HAL) link object.
  parameters:
    acceptHeader:
      name: Accept
      in: header
      description: >-
        Specifies the response format and the
        [version](/api-documentation/docs/reference-guide#versioning) of the API
        to be used.
      required: true
      schema:
        type: string
        enum: [
          "application/vnd.hmrc.2.0+json"
        ]
    contentTypeHeader:
      name: Content-Type
      in: header
      description: The media type of the request body.
      schema:
        type: string
        enum:
          - application/json
      required: true
  securitySchemes:
    userRestricted:
      type: oauth2
      description: >-
        HMRC supports OAuth 2.0 for authenticating user restricted API requests using
        an OAuth 2.0 Bearer Token in the AUTHORIZATION header. See
        https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
        for details.
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.service.hmrc.gov.uk/oauth/authorize'
          tokenUrl: 'https://api.service.hmrc.gov.uk/oauth/token'
          refreshUrl: 'https://api.service.hmrc.gov.uk/oauth/refresh'
          scopes:
            common-transit-convention-guarantee-balance: Access all aspects of guarantee balance.
