openapi: 3.0.3
info:
  title: CTC Guarantee Balance
  version: '1.0'
  contact: {}
servers:
  - url: 'https://test-api.service.hmrc.gov.uk'
    description: Sandbox
  - url: 'https://api.service.hmrc.gov.uk'
    description: Production
    variables: {}
paths:
  /customs/guarantees/balances:
    post:
      operationId: postBalanceRequest
      summary: Send a balance request
      description: >-
        Initiate a balance request. You may receive a response immediately with
        a 200 OK or 400 Bad Request response, or a 202 Accepted response with a
        balance request ID.
      security:
        - userRestricted:
            - write
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - $ref: '#/components/parameters/contentTypeHeader'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - taxIdentifier
                - guaranteeReference
                - accessCode
              properties:
                taxIdentifier:
                  type: string
                  minLength: 1
                  maxLength: 17
                  description: >-
                    The trader identification number (TIN) of the principal on
                    the guarantee.
                  example: GB123456789012
                guaranteeReference:
                  type: string
                  minLength: 1
                  maxLength: 24
                  description: The guarantee reference number (GRN) of the guarantee.
                  example: 20GB0000010000GX1
                accessCode:
                  type: string
                  minLength: 4
                  maxLength: 4
                  description: >-
                    The access code granting access to make use of the
                    guarantee.
                  example: ABC1
      responses:
        '200':
          description: A successful balance request response
          content:
            application/json:
              schema:
                type: object
                required:
                  - response
                properties:
                  _links:
                    type: object
                    description: An object containing links to other resources.
                    properties:
                      self:
                        type: object
                        description: Hypertext Application Language (HAL) object.
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            description: A link to another resource.
                  _embedded:
                    type: object
                    description: An object containing embedded resources.
                  response:
                    type: object
                    description: >-
                      A successful response from the guarantee management
                      system.
                    properties:
                      balance:
                        type: number
                        description: The remaining guarantee balance.
                        example: 12345678.9
                      currency:
                        type: string
                        pattern: '^[A-Z]{3}$'
                        description: >-
                          The alphanumeric three-character ISO currency code of
                          the currency in which the balance is held.
                        example: GBP
        '202':
          description: A pending balance request response
          headers:
            Location:
              required: true
              description: The path of the newly created balance request
              schema:
                type: string
              example: >-
                /customs/guarantees/balances/22b9899e-24ee-48e6-a189-97d1f45391c4
          content:
            application/json:
              schema:
                type: object
                required:
                  - _links
                  - balanceId
                properties:
                  _links:
                    type: object
                    description: An object containing links to other resources.
                    properties:
                      self:
                        type: object
                        description: Hypertext Application Language (HAL) object.
                        required:
                          - href
                        properties:
                          href:
                            type: string
                            description: A link to another resource.
                            example: >-
                              /customs/guarantees/balances/22b9899e-24ee-48e6-a189-97d1f45391c4
                  _embedded:
                    type: object
                    description: An object containing embedded resources.
                  balanceId:
                    type: string
                    description: The ID of the balance request.
                    example: 22b9899e-24ee-48e6-a189-97d1f45391c4
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/functionalErrorResponse'
              example:
                code: FUNCTIONAL_ERROR
                message: The request was rejected by the guarantee management system
                response:
                  errors:
                    errorType: 12
                    errorPointer: GRR(1).Guarantee reference number (GRN)
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              example:
                code: ACCEPT_HEADER_INVALID
                message: The `Accept` header is missing or invalid

  '/customs/guarantees/balances/{balanceId}':
    get:
      operationId: getBalanceRequest
      summary: Check the status of a balance request
      description: >-
        Check the status of a balance request for which a response could not be
        provided immediately. You can use the balance request ID returned by the
        202 Accepted response to call this resource.
      security:
        - userRestricted:
            - read
      parameters:
        - $ref: '#/components/parameters/acceptHeader'
        - name: balanceId
          in: path
          description: The ID of the balance request to check.
          schema:
            type: string
            example: 22b9899e-24ee-48e6-a189-97d1f45391c4
          required: true
      responses:
        '200':
          description: Pending request or Successful request or Failed request
          content:
            application/json:
              schema:
                anyOf:
                  - $ref: '#/components/schemas/pendingRequest'
                  - $ref: '#/components/schemas/successfulRequest'
                  - $ref: '#/components/schemas/failedRequest'
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              example:
                code: NOT_FOUND
                message: The balance request was not found
        '406':
          description: Not Acceptable
          content:
            application/json:
              schema:
                allOf:
                  - $ref: '#/components/schemas/errorResponse'
              example:
                code: ACCEPT_HEADER_INVALID
                message: The `Accept` header is missing or invalid
components:
  schemas:
    errorResponse:
      title: errorResponse
      type: object
      required:
        - code
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error description
    functionalErrorResponse:
      title: functionalErrorResponse
      type: object
      required:
        - code
      properties:
        code:
          type: string
          description: Error code
        message:
          type: string
          description: Error description
        response:
          type: object
          properties:
            errors:
              type: object
              required:
                - errorType
                - errorPointer
              properties:
                errorType:
                  type: number
                  description: The numeric error code of the functional error.
                errorPointer:
                  type: string
                  description: >-
                    The pointer string indicating the data item that was in error.
                errorReason:
                  type: string
                  description: >-
                    The reason message indicating additional information about
                    the cause of the error.
    pendingRequest:
      type: object
      description: Pending request that has not yet received a response
      required:
        - _links
        - request
      properties:
        _links:
          type: object
          description: An object containing links to other resources.
          properties:
            self:
              type: object
              description: Hypertext Application Language (HAL) object.
              required:
                - href
              properties:
                href:
                  type: string
                  description: A link to another resource.
                  example: >-
                    /customs/guarantees/balances/22b9899e-24ee-48e6-a189-97d1f45391c4
        _embedded:
          type: object
          description: An object containing embedded resources.
        request:
          type: object
          description: A request to the guarantee management system.
          required:
            - balanceId
            - taxIdentifier
            - guaranteeReference
            - requestedAt
          properties:
            balanceId:
              type: string
              description: The ID of the balance request.
              example: 22b9899e-24ee-48e6-a189-97d1f45391c4
            taxIdentifer:
              type: string
              description: The tax identifier of the holder of the guarantee.
              example: GB123456789012
            guaranteeReference:
              type: string
              description: The guarantee reference number (GRN) of the guarantee.
              example: 20GB0000010000GX1
            requestedAt:
              type: string
              description: The timestamp when the balance request was created.
              example: '2021-09-14T09:52:15Z'
            completedAt:
              type: string
              description: The timestamp when the balance response was received.
              example: '2021-09-14T09:53:05Z'
            response:
              type: object
              description: The response from the guarantee management system.
    successfulRequest:
      type: object
      description: Successful request that has received a balance response
      required:
        - _links
        - request
      properties:
        _links:
          type: object
          description: An object containing links to other resources.
          properties:
            self:
              type: object
              description: Hypertext Application Language (HAL) object.
              required:
                - href
              properties:
                href:
                  type: string
                  description: A link to another resource.
                  example: >-
                    /customs/guarantees/balances/22b9899e-24ee-48e6-a189-97d1f45391c4
        _embedded:
          type: object
          description: An object containing embedded resources.
        request:
          type: object
          description: A request to the guarantee management system.
          required:
            - balanceId
            - taxIdentifier
            - guaranteeReference
            - requestedAt
          properties:
            balanceId:
              type: string
              description: The ID of the balance request.
              example: 22b9899e-24ee-48e6-a189-97d1f45391c4
            taxIdentifer:
              type: string
              description: The tax identifier of the holder of the guarantee.
              example: GB123456789012
            guaranteeReference:
              type: string
              description: The guarantee reference number (GRN) of the guarantee.
              example: 20GB0000010000GX1
            requestedAt:
              type: string
              description: The timestamp when the balance request was created.
              example: '2021-09-14T09:52:15Z'
            completedAt:
              type: string
              description: The timestamp when the balance response was received.
              example: '2021-09-14T09:53:05Z'
            response:
              type: object
              description: The response from the guarantee management system.
              required:
                - balance
                - currency
              properties:
                status:
                  type: string
                  description: Response status
                  example: SUCCESS
                balance:
                  type: number
                  description: The remaining guarantee balance.
                  example: 12345678.9
                currency:
                  type: string
                  pattern: '^[A-Z]{3}$'
                  description: >-
                    The alphanumeric three-character ISO currency code of the
                    currency in which the balance is held.
                  example: EUR
    failedRequest:
      type: object
      description: Request that has received a functional error response
      required:
        - _links
        - request
      properties:
        _links:
          type: object
          description: An object containing links to other resources.
          properties:
            self:
              type: object
              description: Hypertext Application Language (HAL) object.
              required:
                - href
              properties:
                href:
                  type: string
                  description: A link to another resource.
                  example: >-
                    /customs/guarantees/balances/22b9899e-24ee-48e6-a189-97d1f45391c4
        _embedded:
          type: object
          description: An object containing embedded resources.
        request:
          type: object
          description: A request to the guarantee management system.
          required:
            - balanceId
            - taxIdentifier
            - guaranteeReference
            - requestedAt
          properties:
            balanceId:
              type: string
              description: The ID of the balance request.
              example: 22b9899e-24ee-48e6-a189-97d1f45391c4
            taxIdentifer:
              type: string
              description: The tax identifier of the holder of the guarantee.
              example: GB123456789012
            guaranteeReference:
              type: string
              description: The guarantee reference number (GRN) of the guarantee.
              example: 20GB0000010000GX1
            requestedAt:
              type: string
              description: The timestamp when the balance request was created.
              example: '2021-09-14T09:52:15Z'
            completedAt:
              type: string
              description: The timestamp when the balance response was received.
              example: '2021-09-14T09:53:05Z'
            response:
              type: object
              description: A functional error response from the guarantee management system
              required:
                - errors
              properties:
                errors:
                  type: array
                  description: >-
                    The functional errors returned when attempting to make the
                    balance request.
                  items:
                    $ref: '#/components/schemas/functionalErrorResponse'
  responses: {}
  parameters:
    acceptHeader:
      name: Accept
      in: header
      required: true
      description: >-
        Specifies the response format and the
        [version](/api-documentation/docs/reference-guide#versioning) of the API
        to be used.
      schema:
        type: string
        enum:
          - application/vnd.hmrc.1.0+json
    contentTypeHeader:
      name: Content-Type
      in: header
      description: The media type of the request body.
      schema:
        type: string
        enum:
          - application/json
      required: true
  examples: {}
  requestBodies: {}
  headers: {}
  securitySchemes:
    userRestricted:
      type: oauth2
      description: >-
        HMRC supports OAuth 2.0 for authenticating user restricted API requests
        using an OAuth 2.0 Bearer Token in the AUTHORIZATION header. See
        https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints
        for details. <br />**Example:** `Bearer bb7fed3fe10dd235a2ccda3d50fb`
      flows:
        authorizationCode:
          authorizationUrl: 'https://api.service.hmrc.gov.uk/oauth/authorize'
          tokenUrl: 'https://api.service.hmrc.gov.uk/oauth/token'
          refreshUrl: 'https://api.service.hmrc.gov.uk/oauth/refresh'
          scopes:
            'read:common-transit-convention-guarantee-balance': Grants read access
            'write:common-transit-convention-guarantee-balance': Grants write access
  links: {}
  callbacks: {}
